image: maven:3.8.6-openjdk-18

stages:
- build
- test
echo "HELLO WORLD"

build:
  stage: build
  script:
  - mvn package -Dmaven.test.skip
  - mvn package -Dmaven.test.skip

test:
  stage: test
  script:
  - mvn test
